services:
  app:
    build: .
    ports:
      - '4200:4200'
    command: >
      sh -c "dockerize -wait tcp://postgres:5432 -timeout 60s &&
             pnpm run start:prod"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=s@wefjh@`114ASF14
      - PORT=4200
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=academy
      - PG_PASSWORD=ASF@#R@RQW!@RFQWRR@(*FW
      - PG_DB=academy-db
      - ACCESS_TOKEN_EXPIRES_IN=1h
      - ADMIN_EMAIL=g@pivovarov.academy
      - ADMIN_PASSWORD=aF#RFSAdfr2!E#RDQ@!DDSF
    depends_on:
      - postgres
      - caddy

  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=academy-db
      - POSTGRES_USER=academy
      - POSTGRES_PASSWORD=ASF@#R@RQW!@RFQWRR@(*FW
    volumes:
      - postgres-data:/var/lib/postgresql/data

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  postgres-data:
  caddy_data:
  caddy_config: